name: Deploy to GitHub Pages

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ - Deploying to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
  failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: ❌ - Error
        run: echo 'Cannot deploy since Build workflow has failed!'
