name: Deploy to GitHub Pages

on:
  push:
    tags: '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: latest-build
          path: ./dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: ⬆️ - Deploying to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: gh-pages
